version: "3.8"

services:
  postgres:
    image: postgres:17
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      TZ: Asia/Tehran
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gotoko-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: webapp:v1.0.1
    container_name: gotoko_app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_NAME: mydatabase
    ports:
      - "9000:9000"
    networks:
      - gotoko-net
    restart: on-failure

volumes:
  postgres_data:

networks:
  gotoko-net:
    driver: bridge

