stages:
  - test

test_job:
  stage: test
  image: registery.atlasdtco.com/golang:24.0.2-dind
  script:
    - echo " Running tests from external file..."
    - go mod download
    - eho "testing code with unit test!"
  tags:
    - golang
