apiVersion: v1
kind: ConfigMap
metadata:
  name: gotoko-config
  namespace: default
data:
  APP_NAME: "GoTokoApp"
  APP_ENV: "development"
  APP_PORT: "9000"
  DB_HOST: "db"
  DB_NAME: "mydatabase"
  DB_PORT: "5432"
