apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
        portal-backend: "true"
    spec:
      containers:
        - name: webapp
          image: IMAGE_PLACEHOLDER
          ports:
            - containerPort: 8888
          envFrom:
            - configMapRef:
                name: gotoko-config
          volumeMounts:
            - name: log-dir
              mountPath: /var/log/custom-logs/
          
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

      volumes:
        - name: log-dir
          hostPath:
            path: /var/log/custom-logs/
            type: DirectoryOrCreate

